version: 2.1

# Define the build job
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Specify an appropriate image (can change to suit your project)
    steps:
      - checkout  # Pull the code from GitHub repository
      - run:
          name: Build Project
          command: |
            python home.py install
  test:
    docker:
      - image: circleci/python:3.8  # Use the appropriate Docker image
    steps:
      - checkout  # Pull the code from GitHub repository
      - run:
          name: Install pytest
          command: |
            python -m pip install --upgrade pip
            pip install pytest  # Install pytest directly
      - run:
          name: Run Tests with pytest
          command: |
            pytest  test/test_sum1.py # Discover and run all test_*.py files


# Workflow
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
