version: 2.1

# Define jobs
jobs:
  # Build job
  build:
    docker:
      - image: cimg/python:3.10  # Or any language you're using (adjust the image accordingly)
    steps:
      - checkout  # Checkout the code from your repository
      - run:
          name: No dependencies required for build
          command: echo "Skipping dependency installation."

  # Test job
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Testing
          command: echo "Testing"

  # Deploy job
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Deploy
          command : echo "Deployment"

# Define workflows
workflows:
  version: 2
  build_test_deploy_workflow:
    jobs:
      - build
      - test:
          requires:
            - build  # Only run tests after the build job succeeds
      - deploy:
          requires:
            - test  # Only deploy after the test job succeeds
