version: 2.1

# Define the build job
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Specify an appropriate image (can change to suit your project)
    steps:
      - checkout  # Pull the code from GitHub repository
      - run:
          name: Build Project
          command: |
            # Add your build commands here, for example:
            python setup.py install  # or any build command relevant to your project
            python home.py install

# Workflow
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
